[package]
name = "rustc_codegen_clr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ar = "0.9.0"
either = "1.9.0"
lazy_static = "1.4.0"
ntest = "0.9.0"
postcard = { version = "1.0.6", features = ["use-std"] }
serde = { version = "1.0.183", features = ["derive"] }
[lib]
crate-type=["rlib", "cdylib"]
[[bin]]
name = "linker"
test = false
bench = false
[workspace]
members = [
    "mycorrhiza",
]
